config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  belongs_to :questioning_user, class_name: 'User', optional: true

  validates :user, presence: true
  validates :text, presence: true, length: { maximum: 255 }
end

app/models/user.rb
# frozen_string_literal: true

require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest.new('SHA256')
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_USERNAME_REGEX = /\A[0-9a-zA-Z_]*\z/.freeze
  VALID_BACKGROUNDCOLOR_REGEX = /\A[#0-9a-fA-F]{7,7}\z/.freeze

  has_many :questions

  validates :username, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: VALID_USERNAME_REGEX }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :background_color, format: { with: VALID_BACKGROUNDCOLOR_REGEX }, on: :update

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password
  before_validation :username_downcase

  def encrypt_password
    return unless password.present?

    self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
    self.password_hash = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack1('H*')
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
    return user if user.password_hash == hashed_password

    nil
  end

  def username_downcase
    username.downcase!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :load_question, only: %i[show edit update destroy]
  before_action :authorize_user, except: [:create]

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.questioning_user = current_user if current_user.present?

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Only allow a trusted parameter "white list" through.
  def question_params
    if current_user.present? &&
       params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user.present?
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :load_user, except: %i[index create new]
  before_action :authorize_user, except: %i[index new create show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь зарегистрирован!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user.destroy
    redirect_to root_url, alert: 'Пользователь удален!'
  end

  private

  def load_user
    @user = User.find params[:id]
  end

  def authorize_user
    reject_user unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :background_color, :background_image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def sklonjator(size, vopros, voprosa, voprosov)
    if size % 100 >= 5 && size % 100 <= 20
      voprosov

    elsif size % 10 == 1
      vopros

    elsif size % 10 >= 2 && size % 10 <= 4
      voprosa

    else
      voprosov
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>
    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', log_out_path %>
      <% else %>
        <%= link_to 'Зарегистрироваться', sign_up_path,
          class: 'button button-light button-small' %>
        <%= link_to 'Войти', log_in_path,
          class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">

   <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= render partial: 'questions/question', object: @question %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <%= f.submit 'Ответить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short)%>
      <%= 'спросил:' if question.questioning_user_id.present?%>
      <%= link_to question.questioning_user.username, user_path(question.questioning_user_id) if question.questioning_user_id.present?%>
    </div>
  </div>

  <% if question.user == current_user %>

    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашего фона:', class: 'form-label' %>
        <%= f.text_field :background_image, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :background_color, 'Цвет ободка аватарки', class: 'form-label' %>
        <%= f.color_field :background_color, class: 'form-text-filed' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>

    <% end %>

    <div class="form-action buffer-top">
      <%= button_to 'Удалить профиль', user_path(@user), :method => :delete, data: {confirm: 'Точно удалить профиль?'} %>
    </div>   
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
          @<%= user.username %>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-image: url(<%= (@user.background_image) %>);">
  <h1 class="title-index">
    <%= @user.name %>
  </h1>

  <div class="index-buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div" style="border: 5px solid <%= (@user.background_color) %>">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-username buffer-both">
    @<%= @user.username %>
</h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to 'Спроси меня', '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p>вопросов</p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p>ответов</p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p>не отвечено</p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>